name: Benefio
favicon: null
layout_spectrum: 0.74383
typography_spectrum: 1
title: Benefio - Transforming Boring And Complicated Industries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74820537-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e5b9b'
    - '#9cb5d2'
    - '#ffffff'
    - '#5582b2'
    - '#9999cc'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
