name: Benefio
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Benefio - Transforming Boring And Complicated Industries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74820537-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e5b9b'
    - '#9cb5d2'
    - '#ffffff'
    - '#5582b2'
    - '#9999cc'
  brandStrength: 0.5714590593706816
  lightness: 0.2823454502504319
  saturation: 0.2370814038440585
  rhythmicContrast: 0.16492796456441283
purpose: []
